name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:node18.6.0-chrome105-ff104
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4 # use the explicit version number
        with:
          # Specify Browser since container image is compile with Firefox
          build: yarn build
          start: yarn start
          browser: firefox
